### ISSUE TITLE
code for training

### ISSUE THREAD

**Issue by devinxzhang** [valeoai/FOUND#1]
Thanks for your great work! It seems I cannot find the script for the training (maybe I miss it). Could you please share it? Thanks!

**Comment by osimeoni** [comment]
Dear @DevinCheung, you haven't missed it, I will try and share the training code this week. 
Best,

**Comment by osimeoni** [comment]
Dear @DevinCheung, I have uploaded the training code. Hope that helps !

**Comment by devinxzhang** [comment]
@osimeoni Thanks so much!
