### ISSUE TITLE
No module named 'dino.vision_transformer'

### ISSUE THREAD

**Issue by ghost** [valeoai/FOUND#2]
请问这个dino模块是什么，需要我怎么下载呢？

**Comment by osimeoni** [comment]
Hi @bigtiezhu, 

Did you install DINO following: 

```
git clone https://github.com/facebookresearch/dino.git
cd dino; 
touch __init__.py
echo -e "import sys\nfrom os.path import dirname, join\nsys.path.insert(0, join(dirname(__file__), '.'))" >> __init__.py; cd ../;
```

It's explained in the installation section: https://github.com/valeoai/FOUND#installation-of-found

**Comment by osimeoni** [comment]
Closing but let me know if the problem persists. 
Best,
